# Generated by Django 6.0.7 on 2026-07-21 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCQ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the branch was created'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the branch', null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='faculty',
            field=models.ForeignKey(help_text='Parent faculty this branch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='MCQ.faculty'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.CharField(help_text="Unique identifier for the branch (e.g., 'general', 'computer')", max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(help_text="Display name of the branch (e.g., 'General', 'Computer Engineering')", max_length=100),
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the branch was last updated'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, help_text="Hex color code for the category (e.g., '#b226dc')", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the category was created'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the category', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text="Bootstrap icon class for the category (e.g., 'bi-mortarboard-fill')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(help_text="Unique identifier for the category (e.g., 'entrance', 'license')", max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text="Display name of the category (e.g., 'Entrance', 'License')", max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the category was last updated'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='branch',
            field=models.ForeignKey(help_text='Parent branch this chapter belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='MCQ.branch'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the chapter was created'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the chapter content', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='id',
            field=models.CharField(help_text="Unique identifier for the chapter (e.g., 'ch1', 'ch2')", max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(help_text="Display name of the chapter (e.g., 'Chapter 1: Nepal Overview')", max_length=200),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the chapter was last updated'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='category',
            field=models.ForeignKey(help_text='Parent category this faculty belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='MCQ.category'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the faculty was created'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description of the faculty', null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='icon',
            field=models.CharField(blank=True, help_text="Bootstrap icon class for the faculty (e.g., 'bi-building-fill')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.CharField(help_text="Unique identifier for the faculty (e.g., 'cmat', 'ioe')", max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(help_text="Display name of the faculty (e.g., 'CMAT', 'IOE')", max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the faculty was last updated'),
        ),
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(help_text='Parent chapter this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='MCQ.chapter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Option 1'), (1, 'Option 2'), (2, 'Option 3'), (3, 'Option 4')], default=0, help_text='Index of the correct answer (0-3)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the question was created'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Detailed explanation of why the answer is correct', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional URL to an image for the question (e.g., circuit diagrams, traffic signs)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_1',
            field=models.CharField(help_text='First option for the MCQ', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_2',
            field=models.CharField(help_text='Second option for the MCQ', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_3',
            field=models.CharField(help_text='Third option for the MCQ', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_4',
            field=models.CharField(help_text='Fourth option for the MCQ', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='The actual question text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the question was last updated'),
        ),
    ]
